os: linux
dist: bionic
sudo: required
language: node_js
node_js:
  - 'stable'
services:
  - docker
before_script:
  - docker build -t react_tp -f dockerfile .
script:
  - docker run react_tp yarn build
notifications:
  email:
    on_success: never
    on_failure: always
